export const ar = {
  auth: {
    title: 'يانيف',
    subtitle: 'لعبة ورق متعددة اللاعبين',
    nicknamePrompt: 'اختر لقباً للمتابعة إلى الردهة',
    signInWithApple: 'تسجيل الدخول بـ Apple',
    signingIn: 'جارٍ تسجيل الدخول...',
    devMode: 'دخول سريع (تطوير)',
    devName: 'اسم العرض',
    devEnter: 'دخول',
    error: 'فشل تسجيل الدخول. حاول مرة أخرى.',
  },
  lobby: {
    title: 'الردهة',
    greeting: (name: string) => `مرحباً، ${name}!`,
    createTable: 'إنشاء طاولة',
    quickStartBots: 'لعبة سريعة ضد البوتات',
    joinWithCode: 'انضم بكود',
    settings: 'الإعدادات',
    noTables: 'لا توجد طاولات مفتوحة الآن',
    loading: 'جارٍ التحميل...',
    players: (n: number, max: number) => `${n}/${max} لاعبين`,
    waiting: 'في انتظار',
    inProgress: 'قيد اللعب',
    ranked: 'مصنف',
    casual: 'ودي',
    join: 'انضم',
    signOut: 'تسجيل الخروج',
  },
  createTable: {
    title: 'إنشاء طاولة',
    maxPlayers: 'اللاعبون',
    threshold: 'حد يانيف',
    pointsLimit: 'حد النقاط',
    create: 'العب',
    cancel: 'إلغاء',
  },
  joinTable: {
    title: 'الانضمام إلى طاولة',
    codePlaceholder: 'كود الغرفة (4 أرقام)',
    join: 'انضم',
    cancel: 'إلغاء',
    invalidCode: 'يرجى إدخال كود غرفة من 4 أرقام',
    notFound: 'لم نعثر على طاولة بهذا الكود. يمكنك إنشاء واحدة بنفسك.',
    full: 'الطاولة ممتلئة',
    started: 'اللعبة بدأت بالفعل',
  },
  game: {
    yourTurn: 'دورك!',
    waitingFor: (name: string) => `في انتظار ${name}...`,
    handTotal: (n: number) => `المجموع: ${n}`,
    cardsLeft: (n: number) => `${n} ورقات`,
    discard: 'رمي',
    drawFromDeck: 'سحب من الرزمة',
    drawFirst: 'سحب الأول',
    drawLast: 'سحب الأخير',
    callYaniv: 'يانيف!',
    yanivConfirm: 'هل تريد يانيف؟',
    yanivYes: 'نعم، يانيف!',
    yanivCancel: 'إلغاء',
    chat: 'محادثة',
    chatPlaceholder: 'رسالة...',
    send: 'إرسال',
    score: 'النقاط',
    round: (n: number) => `جولة ${n}`,
    startGame: 'بدء اللعبة',
    roomReady: 'الغرفة جاهزة',
    waitingForPlayers: 'في انتظار اللاعبين...',
    waitingForMorePlayers: 'بانتظار انضمام المزيد من اللاعبين.',
    waitingForHostStart: (name: string) => `في انتظار ${name} لبدء اللعبة.`,
    hostCanStart: 'أنت المضيف. ابدأ متى أردت.',
    playersInRoom: (count: number, max: number) => `${count}/${max} لاعبين في الغرفة`,
    roomCodeLabel: 'رمز الغرفة',
    openSeat: 'مقعد فارغ',
    handOnStart: 'سيتم توزيع البطاقات عندما يبدأ المضيف',
    hostLabel: 'المضيف',
    loadingRoom: 'جارٍ تجهيز الطاولة...',
    leaveConfirm: 'هل أنت متأكد أنك تريد مغادرة الطاولة؟',
    leaveYes: 'نعم، غادر',
    leaveCancel: 'إلغاء',
    leaving: 'جارٍ المغادرة...',
    roomCode: (code: string) => `الكود: ${code}`,
    copyCode: 'نسخ الكود',
    copied: 'تم النسخ!',
    shareOnWhatsApp: 'مشاركة عبر WhatsApp',
    shareInvite: (code: string, url: string) => `تعال العب يانيف معي! كود الغرفة: ${code}\n${url}`,
    turnTimer: (n: number) => `الوقت: ${n}ث`,
    eliminated: 'خرج من اللعبة',
    disconnected: 'غير متصل',
    reconnecting: 'جارٍ إعادة الاتصال...',
  },
  round: {
    yanivCalled: (name: string) => `${name} نادى بيانيف!`,
    assaf: (caller: string, assafer: string) => `أساف! ${assafer} أسقط ${caller}`,
    penalty: '+30 عقوبة',
    scoreReset: '🎉 تم إعادة النقاط إلى الصفر!',
    eliminated: (name: string) => `${name} خرج من اللعبة`,
    nextRound: 'الجولة القادمة تبدأ...',
    pointsAdded: (n: number) => `+${n}`,
  },
  gameOver: {
    title: 'انتهت اللعبة',
    winner: (name: string) => `${name} فاز!`,
    youWon: 'فزت!',
    youLost: 'خسرت',
    finalScores: 'النتائج النهائية',
    playAgain: 'العب مرة أخرى',
    lobby: 'العودة إلى الردهة',
  },
  hadabaka: {
    title: 'هدبكه!',
    prompt: (card: string) => `حصلت على ${card} — هل تريد إعادته؟`,
    accept: 'أعد الورقة!',
    waiting: (name: string) => `${name} يفكر في هدبكه...`,
  },
  errors: {
    INVALID_MOVE: 'تركيبة أوراق غير صالحة',
    NOT_YOUR_TURN: 'ليس دورك',
    WRONG_PHASE: 'الإجراء غير مسموح به الآن',
    HAND_TOO_HIGH: 'المجموع مرتفع جداً ليانيف',
    INVALID_DRAW_SOURCE: 'لا يمكن السحب من هذا المصدر',
    CARDS_NOT_IN_HAND: 'الأوراق ليست في يدك',
    SESSION_EXPIRED: 'انتهت الجلسة',
    TABLE_FULL: 'الطاولة ممتلئة',
    TABLE_NOT_FOUND: 'الطاولة غير موجودة',
    GAME_ALREADY_STARTED: 'اللعبة بدأت بالفعل',
    NOT_HOST: 'فقط المضيف يمكنه البدء',
    connection: 'انقطع الاتصال. جارٍ إعادة الاتصال...',
    unknown: 'خطأ غير معروف',
  } as Record<string, string>,
  suits: { S: 'بستوني', H: 'قلوب', D: 'ديناري', C: 'نادي' } as Record<string, string>,
  ranks: {
    A: 'آس', J: 'جاك', Q: 'ملكة', K: 'ملك',
    joker: 'جوكر',
  } as Record<string, string>,
} as const;
