export const en = {
  auth: {
    title: 'Yaniv',
    subtitle: 'Multiplayer Card Game',
    nicknamePrompt: 'Choose a nickname to continue to the lobby',
    signInWithApple: 'Sign in with Apple',
    signingIn: 'Signing in...',
    devMode: 'Quick Sign In (Dev)',
    devName: 'Display Name',
    devEnter: 'Enter',
    error: 'Sign in failed. Please try again.',
  },
  lobby: {
    title: 'Lobby',
    greeting: (name: string) => `Hello, ${name}!`,
    createTable: 'Create Table',
    quickStartBots: 'Quick Game vs Bots',
    joinWithCode: 'Join with Code',
    settings: 'Settings',
    noTables: 'No open tables right now',
    loading: 'Loading...',
    players: (n: number, max: number) => `${n}/${max} players`,
    waiting: 'Waiting',
    inProgress: 'In Progress',
    ranked: 'Ranked',
    casual: 'Casual',
    join: 'Join',
    signOut: 'Sign Out',
  },
  createTable: {
    title: 'Create Table',
    maxPlayers: 'Players',
    threshold: 'Yaniv Threshold',
    pointsLimit: 'Points Limit',
    create: 'Play',
    cancel: 'Cancel',
  },
  joinTable: {
    title: 'Join Table',
    codePlaceholder: 'Room code (4 digits)',
    join: 'Join',
    cancel: 'Cancel',
    invalidCode: 'Please enter a 4-digit room code',
    notFound: "We couldn't find a table with that code. You can create one yourself.",
    full: 'Table is full',
    started: 'Game already started',
  },
  game: {
    yourTurn: 'Your turn!',
    waitingFor: (name: string) => `Waiting for ${name}...`,
    handTotal: (n: number) => `Hand: ${n}`,
    cardsLeft: (n: number) => `${n} cards`,
    discard: 'Discard',
    drawFromDeck: 'Draw from deck',
    drawFirst: 'Draw first',
    drawLast: 'Draw last',
    callYaniv: 'Yaniv!',
    yanivConfirm: 'Call Yaniv?',
    yanivYes: 'Yes, Yaniv!',
    yanivCancel: 'Cancel',
    chat: 'Chat',
    chatPlaceholder: 'Message...',
    send: 'Send',
    score: 'Score',
    round: (n: number) => `Round ${n}`,
    startGame: 'Start Game',
    roomReady: 'Room ready',
    waitingForPlayers: 'Waiting for players...',
    waitingForMorePlayers: 'Waiting for more players to join.',
    waitingForHostStart: (name: string) => `Waiting for ${name} to start the game.`,
    hostCanStart: 'You are the host. Start whenever you are ready.',
    playersInRoom: (count: number, max: number) => `${count}/${max} players in room`,
    roomCodeLabel: 'Room code',
    openSeat: 'Open seat',
    handOnStart: 'Cards will be dealt when the host starts',
    hostLabel: 'Host',
    loadingRoom: 'Setting up the table...',
    leaveConfirm: 'Are you sure you want to leave the table?',
    leaveYes: 'Yes, leave',
    leaveCancel: 'Cancel',
    leaving: 'Leaving...',
    roomCode: (code: string) => `Code: ${code}`,
    copyCode: 'Copy Code',
    copied: 'Copied!',
    shareOnWhatsApp: 'Share on WhatsApp',
    shareInvite: (code: string, url: string) => `Join my Yaniv room! Room code: ${code}\n${url}`,
    turnTimer: (n: number) => `Time: ${n}s`,
    eliminated: 'Eliminated',
    spectating: 'Spectating',
    disconnected: 'Disconnected',
    reconnecting: 'Reconnecting...',
    pausedTitle: 'Game paused',
    pauseAfterDisconnect: 'The bots are waiting for you to come back. Tap continue when you are ready.',
    pauseAfterTimeout: 'The game paused after inactivity. Tap continue to jump back in.',
    continueGame: 'Continue game',
  },
  round: {
    yanivCalled: (name: string) => `${name} called Yaniv!`,
    assaf: (caller: string, assafer: string) => `Assaf! ${assafer} caught ${caller}`,
    penalty: '+30 penalty',
    scoreReset: '🎉 Score reset to zero!',
    eliminated: (name: string) => `${name} eliminated`,
    nextRound: 'Next round starting...',
    nextRoundIn: (n: number) => `Next round starts in ${n}s`,
    pointsAdded: (n: number) => `+${n}`,
  },
  gameOver: {
    title: 'Game Over',
    winner: (name: string) => `${name} wins!`,
    youWon: 'You won!',
    youLost: 'You lost',
    finalScores: 'Final Scores',
    playAgain: 'Play Again',
    lobby: 'Back to Lobby',
  },
  hadabaka: {
    title: 'Hadabaka!',
    prompt: (card: string) => `Got ${card} — throw it back?`,
    accept: 'Throw back!',
    waiting: (name: string) => `${name} is deciding on hadabaka...`,
  },
  errors: {
    INVALID_MOVE: 'Invalid card combination',
    NOT_YOUR_TURN: "It's not your turn",
    WRONG_PHASE: 'Action not allowed right now',
    HAND_TOO_HIGH: 'Hand total too high for Yaniv',
    INVALID_DRAW_SOURCE: 'Cannot draw from that source',
    CARDS_NOT_IN_HAND: 'Cards not in your hand',
    SESSION_EXPIRED: 'Session expired',
    TABLE_FULL: 'Table is full',
    TABLE_NOT_FOUND: 'Table not found',
    GAME_ALREADY_STARTED: 'Game already started',
    GAME_PAUSED: 'The game is paused until a human continues',
    NOT_HOST: 'Only the host can start',
    connection: 'Connection lost. Reconnecting...',
    unknown: 'Unknown error',
  } as Record<string, string>,
  suits: { S: 'Spades', H: 'Hearts', D: 'Diamonds', C: 'Clubs' } as Record<string, string>,
  ranks: {
    A: 'Ace', J: 'Jack', Q: 'Queen', K: 'King',
    joker: 'Joker',
  } as Record<string, string>,
} as const;
