export const ru = {
  auth: {
    title: 'Янив',
    subtitle: 'Многопользовательская карточная игра',
    nicknamePrompt: 'Выберите ник, чтобы продолжить в лобби',
    signInWithApple: 'Войти через Apple',
    signingIn: 'Вход...',
    devMode: 'Быстрый вход (разработка)',
    devName: 'Отображаемое имя',
    devEnter: 'Войти',
    error: 'Ошибка входа. Попробуйте снова.',
  },
  lobby: {
    title: 'Лобби',
    createTable: 'Создать стол',
    quickStartBots: 'Быстрая игра против ботов',
    joinWithCode: 'Войти по коду',
    noTables: 'Нет открытых столов',
    loading: 'Загрузка...',
    players: (n: number, max: number) => `${n}/${max} игроков`,
    waiting: 'Ожидание',
    inProgress: 'В процессе',
    ranked: 'Рейтинговый',
    casual: 'Обычный',
    join: 'Войти',
    signOut: 'Выйти',
  },
  createTable: {
    title: 'Создать стол',
    maxPlayers: 'Игроки',
    threshold: 'Порог Янива',
    pointsLimit: 'Лимит очков',
    create: 'Играть',
    cancel: 'Отмена',
  },
  joinTable: {
    title: 'Войти в стол',
    codePlaceholder: 'Код комнаты (4 цифры)',
    join: 'Войти',
    cancel: 'Отмена',
    notFound: 'Стол не найден',
    full: 'Стол заполнен',
    started: 'Игра уже началась',
  },
  game: {
    yourTurn: 'Ваш ход!',
    waitingFor: (name: string) => `Ждём ${name}...`,
    handTotal: (n: number) => `Сумма: ${n}`,
    cardsLeft: (n: number) => `${n} карт`,
    discard: 'Сбросить',
    drawFromDeck: 'Взять из колоды',
    drawFirst: 'Взять первую',
    drawLast: 'Взять последнюю',
    callYaniv: 'Янив!',
    yanivConfirm: 'Объявить Янив?',
    yanivYes: 'Да, Янив!',
    yanivCancel: 'Отмена',
    chat: 'Чат',
    chatPlaceholder: 'Сообщение...',
    send: 'Отправить',
    score: 'Очки',
    round: (n: number) => `Раунд ${n}`,
    startGame: 'Начать игру',
    roomReady: 'Комната готова',
    waitingForPlayers: 'Ждём игроков...',
    waitingForMorePlayers: 'Ждём, пока присоединятся другие игроки.',
    waitingForHostStart: (name: string) => `Ждём, пока ${name} начнёт игру.`,
    hostCanStart: 'Вы хост. Начинайте, когда будете готовы.',
    playersInRoom: (count: number, max: number) => `${count}/${max} игроков в комнате`,
    roomCodeLabel: 'Код комнаты',
    openSeat: 'Свободное место',
    handOnStart: 'Карты будут розданы, когда хост начнёт игру',
    hostLabel: 'Хост',
    loadingRoom: 'Подготавливаем стол...',
    roomCode: (code: string) => `Код: ${code}`,
    copyCode: 'Копировать код',
    copied: 'Скопировано!',
    turnTimer: (n: number) => `Время: ${n}с`,
    eliminated: 'Выбыл',
    disconnected: 'Отключён',
    reconnecting: 'Переподключение...',
  },
  round: {
    yanivCalled: (name: string) => `${name} объявил Янив!`,
    assaf: (caller: string, assafer: string) => `Ассаф! ${assafer} поймал ${caller}`,
    penalty: '+30 штраф',
    scoreReset: '🎉 Очки сброшены до нуля!',
    eliminated: (name: string) => `${name} выбыл`,
    nextRound: 'Следующий раунд начинается...',
    pointsAdded: (n: number) => `+${n}`,
  },
  gameOver: {
    title: 'Игра окончена',
    winner: (name: string) => `${name} победил!`,
    youWon: 'Вы победили!',
    youLost: 'Вы проиграли',
    finalScores: 'Итоговые очки',
    playAgain: 'Играть снова',
    lobby: 'В лобби',
  },
  hadabaka: {
    title: 'Хадабака!',
    prompt: (card: string) => `Получили ${card} — вернуть?`,
    accept: 'Вернуть!',
    waiting: (name: string) => `${name} решает хадабаку...`,
  },
  errors: {
    INVALID_MOVE: 'Недопустимая комбинация карт',
    NOT_YOUR_TURN: 'Сейчас не ваш ход',
    WRONG_PHASE: 'Действие недоступно',
    HAND_TOO_HIGH: 'Сумма слишком высока для Янива',
    INVALID_DRAW_SOURCE: 'Нельзя взять из этого источника',
    CARDS_NOT_IN_HAND: 'Карты не в вашей руке',
    SESSION_EXPIRED: 'Сессия истекла',
    TABLE_FULL: 'Стол заполнен',
    TABLE_NOT_FOUND: 'Стол не найден',
    GAME_ALREADY_STARTED: 'Игра уже началась',
    NOT_HOST: 'Только хост может начать',
    connection: 'Соединение потеряно. Переподключение...',
    unknown: 'Неизвестная ошибка',
  } as Record<string, string>,
  suits: { S: 'Пики', H: 'Червы', D: 'Бубны', C: 'Трефы' } as Record<string, string>,
  ranks: {
    A: 'Туз', J: 'Валет', Q: 'Дама', K: 'Король',
    joker: 'Джокер',
  } as Record<string, string>,
} as const;
