export const ErrorCode = {
  // Move errors
  INVALID_MOVE: 'INVALID_MOVE',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  WRONG_PHASE: 'WRONG_PHASE',
  HAND_TOO_HIGH: 'HAND_TOO_HIGH',
  INVALID_DRAW_SOURCE: 'INVALID_DRAW_SOURCE',
  CARDS_NOT_IN_HAND: 'CARDS_NOT_IN_HAND',
  // Auth / session
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  // Table / lobby
  TABLE_FULL: 'TABLE_FULL',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  GAME_PAUSED: 'GAME_PAUSED',
  RECONNECT_EXPIRED: 'RECONNECT_EXPIRED',
  NOT_HOST: 'NOT_HOST',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  // Protocol
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
